name: Generate Snake

on:
  schedule:
    # Every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:  # Allow manual triggering of the workflow from the GitHub Actions tab.

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner to execute the job.

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checks out the repository so we can work with its content.

    - name: Generate the snake gif and svg
      uses: Platane/snk@master  # Uses the Platane/snk action to generate the snake.
      id: snake-gif
      with:
        github_user_name: mohamad-abdelkhalek  # Replace with your GitHub username.
        gif_out_path: dist/github-contribution-grid-snake.gif  # Path to save the generated GIF.
        svg_out_path: dist/github-contribution-grid-snake.svg  # Path to save the generated SVG.

    - name: Show git status
      run: git status  # Displays the git status to assist with debugging, if necessary.

    - name: Push changes
      uses: ad-m/github-push-action@master  # Pushes the changes to the repository.
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Uses GitHub token for authentication.
        branch: master  # Pushes to the master branch.
        force: true  # Forces the push to avoid conflicts.

    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.1.3  # Deploys the generated content to GitHub Pages.
      with:
        target_branch: output  # The branch that contains the generated files (GIF, SVG).
        build_dir: dist  # The directory containing the generated files.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Uses GitHub token for authentication.
